name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-20.04
          cc: gcc
        - os: ubuntu-20.04
          cc: clang
        - os: ubuntu-22.04
          cc: gcc
        - os: ubuntu-22.04
          cc: clang
        - os: macos-11
          cc: cc
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: set up APT
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
    - name: check C compiler version
      run:
        ${{matrix.cc}} --version
    - name: build
      run:
        make CC=${{matrix.cc}}
    - name: run tests
      run: |
        prove -v
    - name: run cppcheck
      if: matrix.cc == 'gcc'
      run: |
        sudo apt-get install cppcheck
        cppcheck --error-exitcode=1 *.c
    - name: run shellcheck
      if: matrix.cc == 'gcc'
      run: |
        shellcheck -s sh misc/*.sh

# vim:ts=2 sts=2 sw=2 et

